server:
  port: 9001
  shutdown: graceful
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10
spring:
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 2000 # 2s
      request-read-timeout: 5000 # 5s
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/auth/realms/PolarBookshop
          jwk-set-uri: ${KEYCLOAK_URL:http://polar-keycloak:8080}/auth/realms/PolarBookshop/protocol/openid-connect/certs
  application:
    name: catalog-service
  lifecycle:
  timeout-per-shutdown-phase: 15s
  datasource:
    hikari:
      maximum-pool-size: 5 #maximo de conexoes
      minimum-idle: 3 # minimo de conexoes, ou seja, começa com 3
      idle-timeout: 10000 #tempo limite de ociosidade das conexoes excedentes, ou seja, 5 - 3 = 2, se essas 2 nao serem usadas em 10 seg, seram fechadas
      connection-timeout: 5000
      pool-name: polardb-catalog-pool
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    username: admin
    password: admin
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    show-sql: true


