version: "3.3"
services:

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:8.2.3
    container_name: grafana
    depends_on:
      - loki
      - tempo
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./platform/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards

  loki:
    image: grafana/loki:2.4.0
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:1.2.0
    container_name: tempo
    command: -config.file /etc/tempo-config.yml
    volumes:
      - ./platform/tempo/tempo.yml:/etc/tempo-config.yml
    ports:
      - "3101:3100"     # Tempo
      - "9411:9411"     # Zipkin

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.4.0-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./platform/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  polar-redis:
    image: "redis:6"
    container_name: "polardb-redis"
    ports:
      - 6379:6379

  polardb-catalog:
    image: "postgres:13"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_catalog

  catalog-service:
    image: "fabricio211/catalog-service:latest"
    container_name: "catalog-service"
    depends_on:
      - fluent-bit
    ports:
      - "7001:7001"
      - "9001:9001"
    environment:
      - ZIPKIN_URL=http://tempo:9411
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polardb-catalog:5432/polardb_catalog
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  order-service:
    image: fabricio211/order-service:latest
    container_name: order-service
    ports:
      - "9002:9002"
    environment:
      - ZIPKIN_URL=http://tempo:9411
      - SPRING_PROFILES_ACTIVE=docker
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  dispatcher-service:
    image: "fabricio211/dispacher-service:latest"
    container_name: "polardb-dispatcher"
    ports:
      - "9003:9003"
    environment:
      - ZIPKIN_URL=http://tempo:9411
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  polardb-order:
    image: "postgres:13"
    container_name: "polardb-order-postgresql"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_order

  polarmq-broker:
    image: "rabbitmq:3-management"
    container_name: "polarmq-broker-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  polar-keycloak:
    image: jboss/keycloak:14.0.0
    container_name: "polar-keycloak"
    #volumes:
    #  - ./keycloak:/opt/jboss/keycloak/imports
    #command:
     # - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
