apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: catalog-service
build:
  artifacts:
  - image: fabricio211/catalog-service
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: polardb-catalog
        chartPath: bitnami/postgresql
        remote: true
        setValues:
          postgresqlUsername: admin
          postgresqlPassword: admin
          postgresqlDatabase: polardb_catalog
          image.tag: 13
  kubectl:
    manifests:
    - k8s/catalog.yml
