apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-app
  labels:
    name: dispatcher-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dispatcher-app
  template:
    metadata:
      labels:
        app: dispatcher-app
    spec:
      containers:
      - image: fabricio211/dispacher-service:latest
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9003
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 20
          periodSeconds: 40
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9003
          initialDelaySeconds: 15
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 20
          periodSeconds: 50
        name: dispatcher-app
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 700Mi
            cpu: "300m"
          requests:
            memory: 700Mi
            cpu: "300m"
---
kind: Service
apiVersion: v1
metadata:
  name:  dispatcher-service
spec:
  selector:
    app:  catalog-app
  type:  ClusterIP
  ports:
    - protocol:  TCP
      port:  8080
      targetPort:  8080