apiVersion: apps/v1
kind: Deployment
metadata:
  name:  order-app
  labels:
    app:  order-app
spec:
  selector:
    matchLabels:
      app: order-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  order-app
    spec:
      containers:
      - name:  order-app
        image:  fabricio211/order-service:latest
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9002
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 20
          periodSeconds: 40
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9002
          initialDelaySeconds: 15
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 20
          periodSeconds: 50
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        ports:
        - containerPort:  9003
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003