name: CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run unit and integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
          java-package: jdk
          architecture: x64
      - name: Gradle build (assemble + test)
        run: |
          chmod +x gradlew
          ./gradlew build
  package:
    name: Package and Publish Image
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Containerize
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage
      - name: Push to Docker hub
        run: docker push fabricio211/catalog-service:0.0.2-SNAPSHOT
