server:
  port: 9003
spring:
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  application:
    name: dispacher-service
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: polar-dispatcher
        packlabel-out-0:
          destination: order-dispatched
  rabbitmq:
    host: polarmq-broker-rabbitmq
    port: 5672
    username: user
    password: password
    connection-timeout: 15s

management:
  endpoints:
    web:
      exposure:
        include: health, heapdump, info, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}