apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: catalog-app

configMapGenerator:
  - name: catalog-app
    files:
      - application.yml

secretGenerator:
  - name: catalog-service
    literals:
      - spring.datasource.password=admin
      - spring.datasource.username=admin
resources:
  - deployment.yml
  - service.yml